name: Build MacOS Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build the MacOS Executable (.app)
      run: |
        pyinstaller --windowed --osx-bundle-identifier=com.seuapp.estoque estoque.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MacOS-App
        path: dist/*.app
