name: Build Cross-Platform Applications

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build Windows App
        run: pyinstaller --onefile --windowed estoque.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-App
          path: dist/estoque.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build macOS App
        run: pyinstaller --onefile --windowed --osx-bundle-identifier=com.seuapp.estoque estoque.py

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: MacOS-App
          path: dist/estoque.app
